name: Build Statics
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: cache 11ty data
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: 11ty_cache
      
      - name: Install dependencies
        run: npm ci
        
      - name: build project
        run: NODE_ENV=production npm run build

