name: Build Statics
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish_page:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cache 11ty data
        uses: actions/cache@v2
        with:
          path: .cache
          key: 11ty_cache
      - name: Install dependencies
        run: npm ci
      - name: build project
        run: NODE_ENV=production npm run build
      - name: publish
        uses: bluebrown/publish-to-s3@v1
        with:
          cluster: eu-central-1
          bucket: rainbowstack.dev
          destination: /website/
          object: 'dist/*'
          recursive: true
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
