name: Build Statics
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: node modules and 11ty data
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            .cache
      
      - name: Install dependencies
        run: npm install
        
      - name: build project
        run: NODE_ENV=production npm run build
